$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'loan_creator'

require 'simplecov'
SimpleCov.start

require 'csv'
require './spec/support/a_valid_lender_timetable.rb'

require './spec/support/big_decimal_helper.rb'

RSpec.configure do |c|
  c.include BigDecimalHelper

  TOLERANCE_THRESHOLD = BigDecimal('0.1', LoanCreator::BIG_DECIMAL_DIGITS).freeze

  # CSV columns:
  CSV_COL_INDEX = 0
  CSV_COL_DATE = 1
  CSV_COL_CRD_BEGINNING_OF_PERIOD = 2
  CSV_COL_CRD_END_OF_PERIOD = 3
  CSV_COL_PERIOD_THEORIC_INTERESTS = 4
  CSV_COL_DELTA_INTERESTS = 5
  CSV_COL_ACCRUED_DELTA_INTERESTS = 6
  CSV_COL_AMOUNT_TO_ADD = 7
  CSV_COL_PERIOD_INTERESTS = 8
  CSV_COL_PERIOD_CAPITAL = 9
  CSV_COL_TOTAL_PAID_CAPITAL_END_OF_PERIOD = 10
  CSV_COL_TOTAL_PAID_INTERESTS_END_OF_PERIOD = 11
  CSV_COL_PERIOD_AMOUNT_TO_PAY = 12

  CAPITAL_RELATED_COLUMNS = [
    CSV_COL_CRD_BEGINNING_OF_PERIOD,
    CSV_COL_CRD_END_OF_PERIOD,
    CSV_COL_PERIOD_CAPITAL,
    CSV_COL_TOTAL_PAID_CAPITAL_END_OF_PERIOD
  ].freeze

  INTERESTS_RELATED_COLUMNS = [
    CSV_COL_PERIOD_THEORIC_INTERESTS,
    CSV_COL_DELTA_INTERESTS,
    CSV_COL_ACCRUED_DELTA_INTERESTS,
    # CSV_COL_AMOUNT_TO_ADD,
    CSV_COL_PERIOD_INTERESTS,
    CSV_COL_TOTAL_PAID_INTERESTS_END_OF_PERIOD
  ].freeze
end
